name: CD
on:
  push:
    tags:
    - '*'
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
    - name: Checkout source
      uses: actions/checkout@v4
    - name: Publish
      run: cargo publish
